### ISSUE TITLE
CodeFlow/AuthorizationServer sample not working with ASP.NET Core 1.1.0

### ISSUE THREAD

**Issue by adrien-constant** [openiddict/openiddict-core#301] opened 2016-12-21 13:57 UTC
Running the sample with ASP.NET Core 1.1.0 does not work.
If you launch AuthorizationServer and ClientApp, and you click on the "sign in" button from the client app, you get the error page.

After investigating the issue, it seems that the controller methods with [Authorize] attribute do not redirect properly to the login page.

Thus, authentication failed, and the server answers with a 401 Not Authorized HTTP error code.

Is it supposed to work only with ASP.NET 1.0.x ? 

[project.json](https://github.com/openiddict/openiddict-core/files/666489/project.json)

**Comment by kevinchalet** [comment] 2016-12-21 14:23
Duplicate of https://github.com/openiddict/openiddict-samples/issues/25.

https://github.com/openiddict/openiddict-core/pull/273
https://github.com/aspnet/Security/issues/1062

**Closed as completed by kevinchalet** 2016-12-21 14:23 UTC
Labels: duplicate
