### ISSUE TITLE
Exact token validation

### ISSUE THREAD

**Issue by alex-dan-s** [openiddict/openiddict-core#1254] opened 2021-05-03 15:31 UTC
Hello!

When I send the token in the header like this:

![image](https://user-images.githubusercontent.com/55558302/116895665-0b510e80-abf9-11eb-8219-0d657ae85a26.png)

The token works well, the problem is that it allows to add extra characters at the end of the token and it is still valid.
This is the original token:

![image](https://user-images.githubusercontent.com/55558302/116895528-ebb9e600-abf8-11eb-9665-8d77d5d9c4d5.png)

After one character:

![image](https://user-images.githubusercontent.com/55558302/116894995-50c10c00-abf8-11eb-91ca-0308d46367df.png)

But sometimes when adding more characters its not valid:

![image](https://user-images.githubusercontent.com/55558302/116894885-2e2ef300-abf8-11eb-976a-dc731237fd78.png)

I looked already in the forums but it seems like no one is facing this problem, or at least is not relevant.
I'm using a password grant type for generating the token following the samples.

https://github.com/openiddict/openiddict-samples

To protect the route I also use this attribute in the method:

 [HttpPost]
 [Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]

### Further technical details
- ASP.NET Core version: 3.1
- OpenIddict.AspNetCore 3.0.3
- OpenIddict.EntityFrameworkCore 3.0.3
- SQL Server 2008

**Comment by kevinchalet** [comment] 2021-05-04 17:38
Hi @alex-dan-s,

Thanks for your report. I was able to reproduce this issue and as I suspected, it's not caused by OpenIddict but by the underlying lib it uses to create and validate JWTs, IdentityModel. I pinged the PM who owns this stack at Microsoft so they can take a look. I'll get back to you when I hear back from the Azure AD team.

Cheers.

**Comment by kevinchalet** [comment] 2021-05-06 16:30
@alex-dan-s FYI, this issue is now tracked by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1641.

**Comment by alex-dan-s** [comment] 2021-05-06 17:30
> 
> 
> Hi @alex-dan-s,
> 
> Thanks for your report. I was able to reproduce this issue and as I suspected, it's not caused by OpenIddict but by the underlying lib it uses to create and validate JWTs, IdentityModel. I pinged the PM who owns this stack at Microsoft so they can take a look. I'll get back to you when I hear back from the Azure AD team.
> 
> Cheers.

Thank you very much :)

**Comment by kevinchalet** [comment] 2021-05-13 15:01
Closing as this issue is tracked externally.

**Closed as completed by kevinchalet** 2021-05-13 15:01 UTC
Labels: bug, external
