### ISSUE TITLE
Hosting the Mvc.Server project on IIS with net451 not working

### ISSUE THREAD

**Issue by ibrmohammed** [openiddict/openiddict-core#105] opened 2016-05-08 09:52 UTC
## Publishing Mvc.Server

<h4>Commands Used</h4>

dotnet publish --configuration Release --runtime win81-x64 --framework "net451"

<h4>Publish Results</h4>

![image](https://cloud.githubusercontent.com/assets/5870046/15097107/30240c8c-152f-11e6-951f-b6fba1ae0c9c.png)
## Hosting on IIS

<h3>Issues seen while hosting on IIS</h3>

![image](https://cloud.githubusercontent.com/assets/5870046/15097138/d4343658-152f-11e6-8aa2-5237110f9f9c.png)

![image](https://cloud.githubusercontent.com/assets/5870046/15097143/fc53d698-152f-11e6-8638-4f482d64e718.png)

<h3>More Info</h3>

The page just kept loading
P.S: Hositng using netcoreapp1.0 is absolutely working fine.

<h3> Web.config</h3>

![image](https://cloud.githubusercontent.com/assets/5870046/15097169/a95234c0-1530-11e6-822b-16cfc991a824.png)

**Comment by kevinchalet** [comment] 2016-05-08 12:11
By quickly looking at the log, I'd say that's because the native Libuv DLL cannot be found.

Sadly, I have no idea why it's happening. I'd recommend pinging someone from the ASP.NET team (e.g @moozzyk, who's the "IIS publish" specialist :smile:)

**Comment by guardrex** [comment] 2016-05-09 00:17
The Application log Error code is the same one that is received for ...

> If you published a self-contained application, confirm that you didn't set a platform in buildOptions of project.json that conflicts with the publishing RID. For example, do not specify a platform of x86 and publish with an RID of win81-x64 (i.e., dotnet publish -c Release -r win81-x64). The project will publish without warning or error but fail with the above logged exceptions on the server.

It's not likely that that applies here, so I'm all :ear:'s on the cause of this, because I'd like to distinguish between these two exceptions in the IIS doc.

**Comment by ibrmohammed** [comment] 2016-05-09 03:40
No. The platform is not set.

## compilation options

  "compilationOptions": {
    "debugType": "portable",
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

Another info that i would like to add is when i published using netcoreapp1.0, i got the following folder structure
refs
runtimes
Views
wwwroot

But with net451,  runtimes folder is missing.

**Comment by moozzyk** [comment] 2016-05-09 15:57
Can you try running your application without IIS? I expect it will fail the same way. If it does, can you check (e.g. using process monitor) where it is trying to load libuv from? Is libuv.dll there? There can be a few causes of failing to load a dll - from the library not being in the target path to missing dependecies to bitness mismatch.

**Comment by moozzyk** [comment] 2016-05-09 17:36
Looks like the issue is in dotnet publish where libuv.dll is not published if you publish for full .NET and non-win7-x64 RID: https://github.com/dotnet/cli/issues/2956. For now stick to `--runtime win7-x64`

**Comment by kevinchalet** [comment] 2016-05-09 17:56
Ah great, that explains why I was unable to reproduce it on my Windows 7 machine, since I was using `win7-x64` and not the buggy `win81-x64` :smile: 

Thanks for investigating :clap: 

Closed as external.

**Comment by dasMulli** [comment] 2016-05-09 18:34
Adding the

``` json
"Microsoft.NETCore.Platforms": "1.0.1-*"
```

dependency to the project.json of `Mvc.Server` seems to make it publish including the native dependencies as it provides a `runtime.json` that defines the needed [`#import` definitions](https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json).

**Comment by guardrex** [comment] 2016-05-09 18:42
@dasMulli Indeed ... yes! I should have looked earlier. The deps do not pull ...
`Microsoft.NETCore.App`, so there is no pull on `NETStandard.Library`, so there is no pull on `Microsoft.NETCore.Platforms`, so ... :boom:

[EDIT] I could expand the guidance for `Publishing to IIS` to include this. /cc @shirhatti, would you like me to add this? ... or do you feel that this really isn't an IIS-thingy? It is kind'a more of a bug in the app dependencies that results in an app that can't run. On the other hand, the current exception for that error code is there because publishing with a platform bitness difference from the publish RID results in this exception. It could be that a dev has the right platform and the right RID and is publishing correctly but will hit this because their deps don't include the platforms package. Of course, that also means that they didn't follow the samples ... something we hope devs will not do.

**Comment by kevinchalet** [comment] 2016-05-11 05:38
Reopening, as we'll have to fix the samples to include the `Microsoft.NETCore.Platforms` package under `net451/dependencies`.

**Comment by kevinchalet** [comment] 2016-05-12 03:10
Fixed: https://github.com/openiddict/openiddict-core/commit/b08a25cc5813a7cf48cdb4e67f31093639bc6e1b.

**Closed as completed by kevinchalet** 2016-05-12 03:10 UTC
Labels: bug

**Comment by jkpindahbc** [comment] 2016-06-07 21:06
This appears to still be broken for net451.

**Comment by kevinchalet** [comment] 2016-06-07 21:10
> This appears to still be broken for net451.

You should spend 2 or 3 minutes trying to explain what doesn't work exactly. Or maybe it was just some random rant? :smile:
