### ISSUE TITLE
How to add a property to a jwt token

### ISSUE THREAD

**Issue by Tsjerno** [openiddict/openiddict-core#673] opened 2018-10-09 14:47 UTC
Hi, 
We're using openiddict in combination with orchard core. With orchard core, we've created an openid server. Server works fine. We'd like to add an extra property to our jwt token. So a resource server can filter the content which is returned based on information in the jwt-token.

Like the current items in our jwt "aud": "oct:Default",  "azp": "client", we would like to add an extra property "org": "Contoso".
What is the best practice to add new properties?

**Comment by marcrib** [comment] 2018-10-11 00:19
Hi @Tsjerno 

Add new claims here: https://github.com/openiddict/openiddict-samples/blob/dev/samples/PasswordFlow/AuthorizationServer/Controllers/AuthorizationController.cs#L84-L91

```
var identity = (ClaimsIdentity) principal.Identity;
identity.AddClaim(new Claim(...));
```

Duplicate of https://github.com/openiddict/openiddict-core/issues/671

**Comment by MatthijsKrempel** [comment] 2018-10-11 07:07
`            services.AddOpenIddict()
                .AddServer(options =>
                {
                    options.AddEventHandler<OpenIddictServerEvents.ProcessSigninResponse>(opt =>
                    {
                        var claim = new Claim("CustomClaim", "Contoso");
                        claim.SetDestinations(OpenIdConnectConstants.Destinations.AccessToken);
                        var identity = opt.Context.Ticket.Principal.Identity as ClaimsIdentity;
                        identity?.AddClaim(claim);
                        return Task.CompletedTask;
                    });
                });`

**Closed as completed** 2018-10-12 07:05 UTC
