### ISSUE TITLE
DateTime conversion issue with Npgsql 6 and EF Core 6

### ISSUE THREAD

**Issue by sandord** [openiddict/openiddict-core#1376] opened 2022-01-10 17:24 UTC
### Describe the bug
After upgrading to Npgsql 6 and EF Core 6, I get the following error when OpenIddict tries to persist a token:

    Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported (...)

As can be read [here](https://www.npgsql.org/doc/types/datetime.html), Npgsql now demands `DateTime` instances to have explicitly set their `Kind` to `Utc`.

I'm aware that the legacy behavior can be re-enabled using an `AppContext` switch but somehow that doesn't work for me when running inside a Docker container.

For me, the following hack works as a workaround:

    builder.Entity<OpenIddictEntityFrameworkCoreToken>().Property(n => n.CreationDate)
        .HasConversion(v => v != null ? v.Value.ToUniversalTime() : (DateTime?)null, v => v);

The code goes inside the `OnModelCreating` method in my context class which derives from `IdentityDbContext<T>`. I'm doing the same for the `ExpirationDate` and `RedemptionDate` properties as.

### To reproduce
- Configure the Dantooine.Server sample to persist to PostgreSQL using Npgsql version 6 and EF Core 6
- Obtain a token from `~/connect/authorize`

### Exceptions (if any)
    Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
     ---> System.InvalidCastException: Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
       at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateAndGetLength(DateTime value, NpgsqlParameter parameter)
       at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
       at Npgsql.NpgsqlParameter.ValidateAndGetLength()
       at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)
       at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
       at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
       at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
       at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
       at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
       at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreTokenStore`5.CreateAsync(TToken token, CancellationToken cancellationToken)
       at OpenIddict.Core.OpenIddictTokenManager`1.CreateAsync(TToken token, CancellationToken cancellationToken)
       at OpenIddict.Core.OpenIddictTokenManager`1.CreateAsync(OpenIddictTokenDescriptor descriptor, CancellationToken cancellationToken)
       at OpenIddict.Core.OpenIddictTokenManager`1.OpenIddict.Abstractions.IOpenIddictTokenManager.CreateAsync(OpenIddictTokenDescriptor descriptor, CancellationToken cancellationToken)
       at OpenIddict.Server.OpenIddictServerHandlers.CreateAccessTokenEntry.HandleAsync(ProcessSignInContext context)
       at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
       at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
       at OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandler.SignInAsync(ClaimsPrincipal user, AuthenticationProperties properties)
       at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
       at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Further technical details
- ASP.NET Core version.
  - 6.0
- Include the output of `dotnet --info`.

        .NET SDK (reflecting any global.json):
         Version:   6.0.101
         Commit:    ef49f6213a

        Runtime Environment:
         OS Name:     Windows
         OS Version:  10.0.19044
         OS Platform: Windows
         RID:         win10-x64
         Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

        Host (useful for support):
          Version: 6.0.1
          Commit:  3a25a7f1cc

        .NET SDKs installed:
          3.1.120 [C:\Program Files\dotnet\sdk]
          3.1.416 [C:\Program Files\dotnet\sdk]
          5.0.210 [C:\Program Files\dotnet\sdk]
          6.0.101 [C:\Program Files\dotnet\sdk]

        .NET runtimes installed:
          Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
          Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
          Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
          Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
          Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
          Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
          Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version.

**Comment by kevinchalet** [comment] 2022-01-10 17:38
The OpenIddict EF Core stores always use UTC dates to populate `DateTime` properties so it's not clear where the `DateKind.Unspecified` value comes from. E.g:

https://github.com/openiddict/openiddict-core/blob/02c64fdd90d5d5d54e918b508088f3dce74233fb/src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs#L816-L826

I'd suggest tweaking the sandbox present in this repo to use npgsql and see if you can reproduce it and try to determine where the non-UTC value comes from.

**Comment by sandord** [comment] 2022-01-13 09:52
I've modified the sandbox to use Postgres and it still works properly.

The next step is to run it inside a Docker container network (which is the scenario in which I encountered the problem). I will try to do this soon.

By the way, my host machine runs in GMT+1 while the containers run in GMT+0 (since they are not aware of the host).

**Comment by kevinchalet** [comment] 2022-01-22 16:09
@sandord were you able to find the root cause of that issue?

**Comment by sandord** [comment] 2022-01-22 21:10
Not yet. I was thinking I could try to change the time zone in the container to match the host to see if the problem goes away.

But the best approach would be running the sandbox in a container but I haven't got around to setting that up.

**Comment by kevinchalet** [comment] 2022-01-28 19:49
Closing for now, but feel free to post additional details if you find anything interesting 😃

**Closed as completed by kevinchalet** 2022-01-28 19:49 UTC
Labels: bug

**Comment by JoC0de** [comment] 2022-06-09 15:27
I had the same issue both in my own code and when using OpenIddict the problem is that when `npgsql` reads a `DateTime` property value from the database it sets the `Kind` to `DateTimeKind.Unspecified` then when you try to perform a SQL `UPDATE` that sets the previously read value you get this error. 

So my fix was to add a Conversion that sets all 'DateTime' objects to 'DateTimeKind.Utc' when read (the conversion of @sandord changes the 'Kind' before write). 
Add this to the `DbContext`:
```
/// <inheritdoc />
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    configurationBuilder.Properties<DateTime>().HaveConversion<UtcValueConverter>();
    configurationBuilder.Properties<DateTime?>().HaveConversion<UtcValueConverter>();
    base.ConfigureConventions(configurationBuilder);
}

private class UtcValueConverter : ValueConverter<DateTime, DateTime>
{
    public UtcValueConverter()
        : base(v => v, v => DateTime.SpecifyKind(v, DateTimeKind.Utc))
    {
    }
}
```
I don't know a better solution to fix it. I find it strange that `npgsql` warns you wenn you try to write a non UTC 'DateTime' but when your read it back you don't get it as UTC.
