### ISSUE TITLE
EF Core Nullable Guid Equals exception

### ISSUE THREAD

**Issue by bradmarder** [openiddict/openiddict-core#499] opened 2017-10-31 16:58 UTC
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL90DFN80VSM", Request id "0HL90DFN80VSM:00000007": An unhandled exception was thrown by the application.
System.ArgumentException: Method 'Boolean Equals(System.Guid)' declared on type 'System.IEquatable`1[System.Guid]' cannot be called with instance of type 'System.Nullable`1[System.Guid]'
   at System.Linq.Expressions.Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
   at System.Linq.Expressions.Expression.ValidateStaticOrInstanceMethod(Expression instance, MethodInfo method)
   at System.Linq.Expressions.Expression.ValidateMethodAndGetParameters(Expression instance, MethodInfo method)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.MethodCallExpression.Update(Expression object, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass24_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArrayWithLength>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Collections.Generic.AsyncEnumerableHelpers.<ToArray>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenIddict.EntityFrameworkCore.OpenIddictTokenStore`5.<ListAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenIddict.OpenIddictProvider`4.<TryRevokeTokensAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenIddict.OpenIddictProvider`4.<ProcessSigninResponse>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<SignInAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<SignInAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.SignInResult.<ExecuteResultAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__186.MoveNext()
```

**Comment by kevinchalet** [comment] 2017-11-01 14:47
Any chance you could tell me more about your config? Or better, a way to reproduce that?

**Comment by bradmarder** [comment] 2017-11-01 19:53
Sorry I can't create a full repro right now. I'm not doing anything out of the ordinary aside from setting OpenIddict to use `Guid` as the `TKey`. I'm using the latest .net builds from myget (not the 2.03 patch). It looks like the actual bug is in EFCore code. I tried replicating a smaller example using every combination of Guid/Nullable<Guid> with `.ToArrayAsync()` to no avail. 

```
services.AddDbContextPool<DbContext>(options =>
                options
                    .UseSqlServer("")
                    .UseOpenIddict<Guid>());

services.AddOpenIddict<Guid>(open =>
    open.AddEntityFrameworkCoreStores<DbContext>();
```

**Comment by kloarubeek** [comment] 2017-11-05 21:01
I have the same issue when using `int` as key. I'm using rolling tokens. After I use the refresh token grant it tries to revoke all tokens in `OpenIddictTokens`. In `TryRevokeTokensAsync` there is a for loop to go through all tokens:

`            foreach (var token in await Tokens.FindByAuthorizationIdAsync(identifier, context.RequestAborted))
`
I think the OpenIddictTokens.AuthorizationId is nullable and thefore is not able to perform this lookup in the OpenIddictTokenStore:

```
public virtual Task<ImmutableArray<TToken>> FindByAuthorizationIdAsync([NotNull] string identifier, CancellationToken cancellationToken)
{
...
    var key = ConvertIdentifierFromString(identifier);
    return ListAsync(tokens => tokens.Where(token => token.Authorization.Id.Equals(key)), cancellationToken);
}
```
I'm trying to find a way to solve this in a generic way...

**Comment by dasMulli** [comment] 2017-11-05 21:07
@kloarubeek  Since you're deep in the code already (and I not at a work computer), can you see the actual query performed against the DB? I'm worried that the use of the `.Equals()` method is unable to compile into a SQL query and rather loads **all** token objects into the application to call this method which can be a huge performance issue. When using `==`, it should successfully compile into a SQL query and respect nullability of references (and in case of strings, the database collation)

**Comment by kevinchalet** [comment] 2017-11-05 21:22
> When using ==, it should successfully compile into a SQL query and respect nullability of references (and in case of strings, the database collation)

We can't use `==` as the `Id` property type is generic (`TKey`). That said, I would be extremely surprised if EF wasn't able to build a SQL query with the expect `WHERE` clause as it's the pattern used by the Identity folks for their EF Core stores.

Concerning the bug, I'm fairly confident it worked fine with EF Core 1.0, but I'll try locally before pinging the EF folks.

**Comment by kloarubeek** [comment] 2017-11-05 21:48
@dasMulli I don't see any query that retrieves all tokens. The weird thing is that it sets the status of the token to 'Redeemed', it logs `The token '{Identifier}' was automatically revoked.` and then the exception is thrown.

**Comment by kevinchalet** [comment] 2017-11-06 00:16
Bug confirmed. It impacts both EF Core 1.x and 2.x. Since I think it won't be fixed anytime soon, I'll override the impacted methods in the EF Core/EF stores to retrieve the tokens via the `TAuthorization` `DbSet`:

```csharp
/// <summary>
/// Retrieves the list of tokens corresponding to the specified authorization identifier.
/// </summary>
/// <param name="identifier">The authorization identifier associated with the tokens.</param>
/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
/// <returns>
/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
/// whose result returns the tokens corresponding to the specified authorization.
/// </returns>
public override async Task<ImmutableArray<TToken>> FindByAuthorizationIdAsync([NotNull] string identifier, CancellationToken cancellationToken)
{
    if (string.IsNullOrEmpty(identifier))
    {
        throw new ArgumentException("The identifier cannot be null or empty.", nameof(identifier));
    }

    IQueryable<TToken> Query(IQueryable<TAuthorization> authorizations)
    {
        var key = ConvertIdentifierFromString(identifier);

        return from authorization in authorizations
               where authorization.Id.Equals(key)
               from token in authorization.Tokens
               select token;
    }

    return ImmutableArray.Create(await Query(Authorizations).ToArrayAsync(cancellationToken));
}
```

SQL query:

```sql
SELECT [authorization.Tokens].[Id], [authorization.Tokens].[ApplicationId], [authorization.Tokens].[AuthorizationId], [authorization.Tokens].[Ciphertext], [authorization.Tokens].[CreationDate], [authorization.Tokens].[ExpirationDate], [authorization.Tokens].[Hash], [authorization.Tokens].[Status], [authorization.Tokens].[Subject], [authorization.Tokens].[Timestamp], [authorization.Tokens].[Type]
FROM [OpenIddictAuthorizations] AS [authorization]
INNER JOIN [OpenIddictTokens] AS [authorization.Tokens] ON [authorization].[Id] = [authorization.Tokens].[AuthorizationId]
WHERE [authorization].[Id] = @__key_0
```

**Comment by kloarubeek** [comment] 2017-11-06 08:07
Nice, I'll check this evening if this fixes the problem!

**Comment by kevinchalet** [comment] 2017-11-06 12:52
FYI it also works with an explicit join against the `Tokens` database set:

```csharp
/// <summary>
/// Retrieves the list of tokens corresponding to the specified authorization identifier.
/// </summary>
/// <param name="identifier">The authorization identifier associated with the tokens.</param>
/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
/// <returns>
/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
/// whose result returns the tokens corresponding to the specified authorization.
/// </returns>
public override async Task<ImmutableArray<TToken>> FindByAuthorizationIdAsync([NotNull] string identifier, CancellationToken cancellationToken)
{
    if (string.IsNullOrEmpty(identifier))
    {
        throw new ArgumentException("The identifier cannot be null or empty.", nameof(identifier));
    }

    // Note: due to a bug in Entity Framework Core's query visitor, the tokens can't be
    // filtered using token.Authorization.Id.Equals(key). To work around this issue,
    // this method is overriden to use an explicit join before applying the equality check.
    // See https://github.com/openiddict/openiddict-core/issues/499 for more information.

    IQueryable<TToken> Query(IQueryable<TAuthorization> authorizations, IQueryable<TToken> tokens)
    {
        var key = ConvertIdentifierFromString(identifier);

        return from token in tokens
               join authorization in authorizations on token.Authorization.Id equals authorization.Id
               where authorization.Id.Equals(key)
               select token;
    }

    return ImmutableArray.Create(await Query(Authorizations, Tokens).ToArrayAsync(cancellationToken));
}
```

I'll probably opt for this option instead of the one I initially suggested as it allows using `Include(token => token.Application).Include(token => token.Authorization)` to eagerly load the application and the authorization with the tokens (which is something I plan to do in a future PR).

**Comment by kevinchalet** [comment] 2017-11-06 18:40
FYI Entity Framework 6.x is not impacted by this bug so I'll remove the work around from the EF 6 stores.
For the record, here's the query it generates:

```sql
SELECT 
    1 AS [C1], 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Scopes] AS [Scopes], 
    [Extent1].[Status] AS [Status], 
    [Extent1].[Subject] AS [Subject], 
    [Extent1].[Timestamp] AS [Timestamp], 
    [Extent1].[Type] AS [Type], 
    [Extent1].[ApplicationId] AS [ApplicationId]
    FROM [dbo].[OpenIddictAuthorizations] AS [Extent1]
    WHERE ([Extent1].[ApplicationId] IS NOT NULL) AND ([Extent1].[Subject] = @p__linq__0) AND ([Extent1].[ApplicationId] = @p__linq__1)
```

**Comment by kloarubeek** [comment] 2017-11-06 19:41
I tested the flow and the exception is gone. However, when using RollingTokens flow, when I request a new access token via the refresh token grant, I get a message 'The specified refresh token is no longer valid.'

After the call the token status is 'redeemed', maybe this is done in the wrong order? Or should I create a new issue?

**Comment by kevinchalet** [comment] 2017-11-06 20:24
I can't reproduce that locally. Can you describe the whole process and post your logs?

**Closed as completed** 2017-11-07 12:37 UTC
Labels: bug, external

**Comment by kloarubeek** [comment] 2017-11-07 21:21
@PinpointTownes thanks for the fix, if I have a RollingTokens problem, I'll create a new issue!
