### ISSUE TITLE
id_token_hint validation for RP initiated logout missing?

### ISSUE THREAD

**Issue by ju57u5** [openiddict/openiddict-core#1219] opened 2021-02-24 10:33 UTC
Hi,

I noticed that OpenIdDict doesn't validate the `id_token_hint` provided to the `end_session_endpoint` for RP initiated logouts (at least not in the Velusia sample when it is passed through to MVC). After reading through the code a bit and understanding the event model I noticed, that I can just register my own handler to dispatch a `ProcessAuthenticationContext` to initiate the validation. The handlers behind `ProcessAuthenticationContext` seem all be equiped to handle this scenario and and the code mentions the logout endpoint explicitly [0].

Considering the spec for the RP initiated logout mentions that "When an id_token_hint parameter is present, the OP MUST validate that it was the issuer of the ID Token." [1] I wanted to ask if that step was intentionally left out of the logout event chain or if it is a bug.

Cheers

[0] https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerHandlers.cs#L190
[1] https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

**Comment by kevinchalet** [comment] 2021-02-24 12:27
Hi,

It's deliberate: to keep the UX acceptable, OpenIddict doesn't automatically reject authorization or logout requests specifying an invalid `id_token_hint` (which may be caused by tons of reasons, like a rotation of the signing keys). Applications that want to use `id_token_hint` to modify the request processing logic (typically, to bypass a logout confirmation screen) are invited to use `HttpContext.AuthenticateAsync(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)` to validate the `id_token_hint`: in this case, the full set of validation checks will be applied by OpenIddict (except the expiration date, which is deliberately not checked in this case). If the issuer is not valid, a "failed authentication" result will be returned by the ASP.NET Core `AuthenticateAsync()` method. In this case, the application can either trigger an error or ignore the invalid `id_token_hint` and display a confirmation form (my favorite option, as the UX is much better).

It's also worth noting that OpenIddict doesn't force a client to send an `id_token_hint` parameter when specifying a `post_logout_redirect_uri`, as this requirement is very recent and was not part of the previous drafts (e.g https://openid.net/specs/openid-connect-session-1_0-25.html#RPLogout). I considered changing that in 3.0, but this caused a lot of pain with backward compat', so I finally decided against it.

I guess that's the price to pay for implementing drafts that take years to be adopted 😠

**Closed as completed** 2021-02-24 12:27 UTC
Labels: wontfix
