### ISSUE TITLE
signin with ticket containing scopes do not return scope in response

### ISSUE THREAD

**Issue by dragouf** [openiddict/openiddict-core#603] opened 2018-05-15 08:59 UTC
I'm returning a ticket with a list of scopes when user signin with password flow :

```
var ticket = await CreateTicketAsync(request, user);
ticket.SetScopes(new[] {
    OpenIdConnectConstants.Scopes.OpenId,
    OpenIdConnectConstants.Scopes.Email,
     OpenIdConnectConstants.Scopes.Profile,
     OpenIdConnectConstants.Scopes.OfflineAccess,
});
return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
```

but the json response doen't contain scope property. I obtain something like that :

`{"resource":"resource_server","token_type":"Bearer","access_token":"","expires_in":3600,"refresh_token":"","id_token":""}`

any idea why ?

**Comment by kevinchalet** [comment] 2018-05-15 11:51
To reduce the length of token responses, scopes are only returned if they differ from the requested scopes, as allowed by the specification:

> scope:  OPTIONAL, if identical to the scope requested by the client; otherwise, REQUIRED. The scope of the access token as described by Section 3.3.

https://tools.ietf.org/html/rfc6749#section-5.1

**Comment by dragouf** [comment] 2018-05-15 12:24
ok I see, and is there a way to force to return them always ? 

I use a library which expect it all the time. For the moment I did that :

`ticket.SetProperty("scope#public_string", ticket.GetProperty(OAuthValidationConstants.Properties.Scopes));`

Which seems ugly to me...

**Comment by kevinchalet** [comment] 2018-05-15 13:10
> I use a library which expect it all the time.

Any chance you can tell us what's the library you're using?

> ok I see, and is there a way to force to return them always ?

No. As a general rule, there's usually no option to deal with non-standard clients (otherwise, we'd end up with a ton of options and the configuration API would be a complete mess to work with).

It's worth noting the snippet you suggested won't work as you expect (multi-value properties are stored as JSON, but the `scope` must be returned as a space-separated string).

Instead, do something like that:

```csharp
ticket.SetProperty("scope#public_string", string.Join(" ", ticket.GetScopes()));
```

Once https://github.com/openiddict/openiddict-core/pull/604 is merged, you'll have a second option:

```csharp
public class MyProvider : OpenIdConnectServerProvider
{
    public override Task ApplyTokenResponse(ApplyTokenResponseContext context)
    {
        if (context.Ticket != null && string.IsNullOrEmpty(context.Error))
        {
            // Always return the "scope" response parameter.
            context.Response.Scope = string.Join(" ", context.Ticket.GetScopes());
        }

        return Task.CompletedTask;
    }
}
```

```csharp
services.AddOpenIddict()

    // Register the OpenIddict core services.
    .AddCore(options =>
    {
        // ...
    })

    // Register the OpenIddict server services.
    .AddServer(options =>
    {
        // ...

        options.RegisterProvider<MyProvider>();
    })

    // Register the OpenIddict validation services.
    .AddValidation();
```

**Comment by dragouf** [comment] 2018-05-15 14:01
sorry about the library, it's this one : https://github.com/manfredsteyer/angular-oauth2-oidc

thanks a lot for your quick reply and nice answer.

**Comment by kevinchalet** [comment] 2018-05-15 14:05
Looks like a known issue caused by a recent change: https://github.com/manfredsteyer/angular-oauth2-oidc/issues/309

/cc @manfredsteyer

**Comment by kevinchalet** [comment] 2018-05-17 19:06
Closing, as I believe @manfredsteyer pushed a fixed version :tada:

**Closed as completed by kevinchalet** 2018-05-17 19:06 UTC
Labels: question, external
