### ISSUE TITLE
The specified token is invalid since we renewed SSL certificate in Azure key vault

### ISSUE THREAD

**Issue by AGIS-Development** [openiddict/openiddict-core#2045] opened 2024-03-26 10:00 UTC
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.0.1

### Question

Hi Kevin

Since we renewed the SSL certificate in the Azure key vault, we got the following bad request:
![image](https://github.com/openiddict/openiddict-core/assets/157363207/dd1b5173-ec7a-4c73-8e52-7eb8af06320a)

![image](https://github.com/openiddict/openiddict-core/assets/157363207/459e6e47-9a6d-4160-9e68-9c215c6c2708)

The new ssl certificates are loaded and displayed correctly in the browser.

FYI: We updated the certificate thumbprint for for signing and encryption. We load the certifcate with the app setting "WEBSITE_LOAD_CERTIFICATES"

`options.AddEncryptionCertificate(appSettings.Certificates.EncryptionCertificateThumbprint);
options.AddSigningCertificate(appSettings.Certificates.SigningCertificateThumbprint);`

Do you have any idea how we can solve our issue? Is it a caching problem?

Thanks for your help.

Kind regards
Raphael

**Comment by kevinchalet** [comment] 2024-03-26 13:27
Hey Raphael,

Any chance you could collect and share the logs here (OpenIddict uses the standard `Microsoft.Extensions.Logging` stack)?
Make sure you lower down the default log level to `Trace` before collecting them 😃 

(note: the certificates used by OpenIddict are X.509 certificates but not X.509 TLS certificates, that should only be used for HTTPS).

**Comment by AGIS-Development** [comment] 2024-03-26 14:21
I'm not sure which logs you need exactly.
[Logs.zip](https://github.com/openiddict/openiddict-core/files/14759734/Logs.zip)

FYI: The new SSL certificate is from another issuer "GlobalSign" instead of "DigiCert"

**Comment by kevinchalet** [comment] 2024-03-26 14:24
> I'm not sure which logs you need exactly.

I need the .NET Core/ASP.NET Core logs. More information here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0.

Sadly, your .zip only contains the IIS logs, that can't be used to debug such higher-level issues.

**Comment by AGIS-Development** [comment] 2024-03-26 15:25
Here are the trace logs.

[Azure Monitor Log Analytics Export - 2024-03-26.csv](https://github.com/openiddict/openiddict-core/files/14760782/Azure.Monitor.Log.Analytics.Export.-.2024-03-26.csv)

**Comment by kevinchalet** [comment] 2024-03-26 15:28
Thanks. Sadly these logs are incomplete: I only see a logout request being processed here.

**Comment by AGIS-Development** [comment] 2024-03-26 17:06
Sorry, there was a limit of 100 in the query.

[Azure Monitor Log Analytics Export - 2024-03-26 II.csv](https://github.com/openiddict/openiddict-core/files/14762071/Azure.Monitor.Log.Analytics.Export.-.2024-03-26.II.csv)

**Comment by kevinchalet** [comment] 2024-03-26 17:09
> Sorry, there was a limit of 100 in the query.

No worries. Unfortunately, the call to the `/connect/token` endpoint is still missing 😭

**Comment by AGIS-Development** [comment] 2024-03-26 17:23
Sorry for the inconvenience. Now I have found it.
[Azure Monitor Log Analytics Export - 2024-03-26 - connect-token.csv](https://github.com/openiddict/openiddict-core/files/14762291/Azure.Monitor.Log.Analytics.Export.-.2024-03-26.-.connect-token.csv)

<img width="1211" alt="image" src="https://github.com/openiddict/openiddict-core/assets/157363207/c8f6e19c-31dc-456c-91b9-40c1c7774820">

**Comment by kevinchalet** [comment] 2024-03-26 17:36
Yep, this is indeed the root cause.

Questions:
  - Do you have multiple instances of your authorization server? If so, have you tried to restart them all to ensure the new certificates are used by all the instances?
  - Can you please retry with `IdentityModelEventSource.ShowPII` set to `true`?
  - Can you reproduce the error with self-signed signing and encryption certificates? (which is the approach I would recommend as using certificates issued by a well-known issuer like GlobalSign or DigiCert doesn't add much value: https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html#registering-a-certificate-recommended-for-production-ready-scenarios)

**Comment by AGIS-Development** [comment] 2024-03-26 17:48
1. No, we do not use multiple instances.
2. I will retry it with IdentityModelEventSource.ShowPII set to true.
3. I will try it out with the self-signed signing and encryption certificates

Thank you for your quick answers.

**Comment by AGIS-Development** [comment] 2024-03-26 18:31
Hey Kevin. 

It works with the self-signed signing and encryption certificates :-)

Thank you very much for your support. You are my hero ;-)

Kind regards
Raphael

**Comment by kevinchalet** [comment] 2024-03-27 06:00
> Thank you very much for your support. You are my hero ;-)

Haha, my pleasure! Thanks for sponsoring the project! ❤️ 

Glad to hear it's working fine with self-signed certificates!

But... I'm now wondering why it didn't work with the certificates issued by GlobalSign 😅 
Do you think you could share the public part of one of those certificates - ideally as a .cer file - so I can take a look at its properties?

**Comment by AGIS-Development** [comment] 2024-03-28 07:42
Hi Kevin

Here is the .crt certificate in a zip file.
[Wildcard.zip](https://github.com/openiddict/openiddict-core/files/14785698/Wildcard.zip)

**Comment by kevinchalet** [comment] 2024-04-17 14:33
Ooops, looks like I didn't hit the "comment" button 🤣 

I took a look but couldn't find anything special about that certificate. Doing more digging would require sharing the private key, which isn't something really feasible for a non-self-signed certificate.

Closing but feel free to reopen if necessary.

**Closed as completed by kevinchalet** 2024-04-17 14:33 UTC
Labels: question, sponsor
