### ISSUE TITLE
100% CPU when revoking tokens

### ISSUE THREAD

**Issue by verdie-g** [openiddict/openiddict-core#1819] opened 2023-07-02 20:41 UTC
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

My server sometimes goes 100% CPU and I've noticed the correlation with 2 logs
```
The token '{GUID}' was successfully revoked.
```
and
```
An exception occurred in the database while saving changes for context type 'Crpg.WebApi.Identity.OpenIddictDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Conflicts were detected for instance of entity type 'OpenIddictEntityFrameworkCoreToken' on the concurrency token properties {'ConcurrencyToken'}. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting values.
 at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.ThrowUpdateConcurrencyException(IUpdateEntry entry, Dictionary`2 concurrencyConflicts, IDiagnosticsLogger`1 updateLogger)
 at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Update(IUpdateEntry entry, IDiagnosticsLogger`1 updateLogger)
 at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IList`1 entries, IDiagnosticsLogger`1 updateLogger)
 at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)""","An exception occurred in the database while saving changes for context type 'Crpg.WebApi.Identity.OpenIddictDbContext'.Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Conflicts were detected for instance of entity type 'OpenIddictEntityFrameworkCoreToken' on the concurrency token properties {'ConcurrencyToken'}. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting values. at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.ThrowUpdateConcurrencyException(IUpdateEntry entry, Dictionary`2 concurrencyConflicts, IDiagnosticsLogger`1 updateLogger) at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Update(IUpdateEntry entry, IDiagnosticsLogger`1 updateLogger) at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IList`1 entries, IDiagnosticsLogger`1 updateLogger) at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

Here are the logs filtering on "OpenIddict" or "error": [openiddict-logs.csv](https://github.com/openiddict/openiddict-core/files/11931365/openiddict-logs.csv).

For info, I'm using the in-memory provider. I'm thinking that maybe the token revocation expects an index so it's super slow with this provider?

### To reproduce

Hard to reproduce. Use this program and make it run for days https://github.com/verdie-g/crpg/blob/844795b4c2b6c32431a4ff6bf75ce938a9a9d72e/src/WebApi/Program.cs

**Comment by kevinchalet** [comment] 2023-07-03 14:13
Hi 👋🏻 

Well, the in-memory provider has never been considered production-ready by the EF team and they even talked about removing it at some point (and encouraging using the SQLite provider instead): it's still supported, but not really actively developed and only recommended for things like unit tests.

Also, your application doesn't seem to use the Quartz integration to do some cleanup at regular intervals, so it's very likely the in-memory DB grows to a point where the tokens table is too big to be scanned.

That said, automatic revocation only occurs when an authorization code or a refresh token is replayed by a client, which is generally a pathological case: you may want to check whether your clients are not trying to redeem an authorization code twice and don't try to replay a refresh token after the 30-second reuse leeway (customizable via `OpenIddictServerBuilder.SetRefreshTokenReuseLeeway()`).

Note: even with a real DB, the token/authorization revocation logic used for replay detection is not super efficient, but improving that will require new store methods, which can only happen in a major version.

**Comment by verdie-g** [comment] 2023-07-05 13:04
Thank you for the detailed answer. I'll try to understand what's wrong with my client.

**Comment by verdie-g** [comment] 2023-07-05 15:04
Could concurrent queries to the token endpoint using client credentials cause that issue?

https://github.com/verdie-g/crpg/blob/4f516ffa71228e4363766bc5629478f7e54ef729/src/Module.Server/Api/HttpCrpgClient.cs#L172-L181

**Comment by kevinchalet** [comment] 2023-07-05 15:17
No, the replay detection/revocation mechanism only kicks in when using an authorization code or refresh token (i.e not when using the client credentials grant)

**Comment by verdie-g** [comment] 2023-07-05 17:00
> redeem an authorization code twice

I'm using [oidc-client-ts](https://github.com/authts/oidc-client-ts) so that would be a bug in that library which sounds unlikely.

> try to replay a refresh token after the 30-second reuse leeway

Maybe I can disable refresh tokens altogether.

Is it expected that the revocations are performed by thousands?
![image](https://github.com/openiddict/openiddict-core/assets/9092290/4fc1bfa3-94bb-4166-ace2-08c7d4a0f141)

Also I can see the token endpoint called several times. I could be because the user has several tabs/windows open. Does that induce revocation or each tab will have its own token. I guess I'm a bit confused about how the token store is indexed.
![image](https://github.com/openiddict/openiddict-core/assets/9092290/190de117-fa4f-49cd-ae3f-511cd1bc2f20)

**Comment by kevinchalet** [comment] 2023-07-10 15:03
> Is it expected that the revocations are performed by thousands? ![image](https://user-images.githubusercontent.com/9092290/251224869-4fc1bfa3-94bb-4166-ace2-08c7d4a0f141.png)

Given that you're never flushing the authorizations/tokens from the DB, if you have very active users for which tons of tokens end up being attached to the same authorization, it can quickly make the list grows (a token entry is created for each type of generated token). And all these token entries have to be marked as revoked when a replay is thought to be detected.

> Also I can see the token endpoint called several times. I could be because the user has several tabs/windows open. Does that induce revocation or each tab will have its own token. I guess I'm a bit confused about how the token store is indexed. ![image](https://user-images.githubusercontent.com/9092290/251229718-190de117-fa4f-49cd-ae3f-511cd1bc2f20.png)

It doesn't seem your app uses a custom access token lifespan, so the default value - 1 hour - should be used. Given you're using `userStore: new WebStorageStateStore({ store: window.localStorage })` (https://github.com/verdie-g/crpg/blob/844795b4c2b6c32431a4ff6bf75ce938a9a9d72e/src/WebUI/src/services/auth-service.ts#L34C3-L34C71), it's not clear at all to me why the authentication context wouldn't be preserved across tabs and why multiple token requests are sent at such small intervals. Can you reproduce the issue locally? If so, it would help to collect some `oidc-client-ts` logs to see what could be causing that.

**Comment by verdie-g** [comment] 2023-07-14 20:17
By opening 20 tabs I was able to reproduce the `DbUpdateConcurrencyException` when the token gets refreshed but no revoked token logs.

**Comment by kevinchalet** [comment] 2023-07-14 21:01
> By opening 20 tabs I was able to reproduce the `DbUpdateConcurrencyException` when the token gets refreshed but no revoked token logs.

`DbUpdateConcurrencyException`s are expected and caught by OpenIddict to return valid responses, so it's not an error in itself. That said, it clearly indicates the client doesn't reuse the existing authentication state and redeems the same refresh token multiple times.

**Comment by verdie-g** [comment] 2023-07-24 14:26
A new occurence didn't show any "token revoked" logs. The only weird pattern that I could find is a single user spamming token requests. Here is a sample:
```
2023-07-24T03:15:58.035Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
2023-07-24T03:15:58.038Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
2023-07-24T03:16:05.720Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:05.823Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T03:16:06.066Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
2023-07-24T03:16:06.066Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
2023-07-24T03:16:06.066Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
2023-07-24T03:16:06.066Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
2023-07-24T03:16:06.066Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
2023-07-24T03:16:06.066Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
```
22x200 + 87x499 + 87x502

Then 1 hour later, just
```
2023-07-24T04:15:07.887Z,POST https://api.c-rpg.eu/connect/token 200 SA.ME.I.P
```
1x200

And 1 hour later again
```
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.108Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.797Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.798Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.798Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:17.799Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:18.210Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:18.210Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:18.210Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:18.210Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:18.210Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:18.210Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:18.210Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
2023-07-24T05:14:18.210Z,POST https://api.c-rpg.eu/connect/token 499 SA.ME.I.P
```
1x408 + 667x499 + 146x502

That sounds like an issue in the client but can it impact OpenIddict? And if it does, is there anything it can do to protect itself?

**Comment by kevinchalet** [comment] 2023-07-24 15:13
> That sounds like an issue in the client but can it impact OpenIddict?

At this point, it even looks like a malicious client 😅 
499 errors indicate the HTTP client reset the connection, which is the sign something suspicious is happening, given the extremely short intervals between each requests.
Do you store a contact email with your client registrations that would allow you to contact the owner of the misbehaving client?

That said, unless you're seeing CPU spikes during these requests, it shouldn't affect your authorization server.

> And if it does, is there anything it can do to protect itself?

OpenIddict relies on the host to handle such things. If you're seeing perf' impacts because of these requests, you can revoke the client identifier or use [ASP.NET Core 7's rate limiting middleware](https://blog.maartenballiauw.be/post/2022/09/26/aspnet-core-rate-limiting-middleware.html) to throttle the requests before they reach OpenIddict.

Please keep me informed 👍🏻

**Comment by verdie-g** [comment] 2023-07-24 15:24
> Do you store a contact email with your client registrations that would allow you to contact the owner of the misbehaving client?

Actually I only have 2 clients. https://github.com/verdie-g/crpg/blob/master/deploy/roles/crpg-web-api/templates/appsettings.Production.json.j2#L19-L51
The first one is https://c-rpg.eu and the second one is using client credentials and is only used be myself.

I've open an issue here https://github.com/authts/oidc-client-ts/issues/1102 because it looked like a bad retry mechanism to me.

**Comment by kevinchalet** [comment] 2023-07-24 15:27
What's weird is that all these requests come from the same IP address. Maybe someone is impersonating your legitimate client with a different library. That would be useful to log the user agent headers to see if you find anything interesting.

**Comment by verdie-g** [comment] 2023-07-24 15:37
I've thought about that, the user-agent is 
```
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; Valve Steam GameOverlay/1689034492) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
```
and the IP comes from a players with ~15 days of play time so I would tend to think of an issue in the client library.

Now that I read the user-agent again
> Valve Steam GameOverlay

Steam games have an overlay where you can open a browser that is known to be old and broken. 🤷‍♂️

Also I'll try to disable the silent authentication on oidc-client-ts. It still a bit blurry to me how the re-authentication works without impacting the UX.

**Comment by verdie-g** [comment] 2023-08-01 17:45
We have a good hypothesis: before each request we would [call signInSilent](https://github.com/verdie-g/crpg/blob/4cec3430ef8eccb18df91c9eadc910f5a206c632/src/WebUI/src/services/crpg-client.ts#L25) but if several requests were performed at the same time (e.g. sometimes we would do Promise.all(req1, req2, ...), then the token requests for the first request wouldn't be done before the second request started executing and several token requests would be sent.

**Comment by kevinchalet** [comment] 2023-08-04 13:41
@verdie-g makes a lot of sense (tho' it's not clear to me why only a single user seems to be affected).

Given it's likely not an OpenIddict issue at this point, I'm going to close this ticket. I opened https://github.com/openiddict/openiddict-core/issues/1856 to track adding new store methods in 5.0 to make the token chain revocation process much more efficient.

Cheers.

**Closed as completed by kevinchalet** 2023-08-04 13:41 UTC
Labels: bug, sponsor
