### ISSUE TITLE
The number of primary key values passed must match number of primary key values defined

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#502] opened 2017-11-06 13:53 UTC
I have updated to the latest version of openiddict, deleted my tables, removed the migration entry and my tables are all created again, thats fine.

Problem is now, when i try to login i get the following exception

> The number of primary key values passed must match number of primary key values defined on the entity. 
> Parameter name: keyValues

Any idea why?  Seems to happen after the `Exchange` method in my `AuthorizationController.cs` file, which seems to execute successfully.  

Here is some basic details if it helps

![image](https://user-images.githubusercontent.com/7406381/32444179-8f583254-c2f9-11e7-8d8b-4446c9524123.png)

> at System.Data.Entity.Internal.WrappedEntityKey..ctor(EntitySet entitySet, String entitySetName, Object[] keyValues, String keyValuesParamName)\r\n   at System.Data.Entity.Internal.Linq.InternalSet`1.<FindInternalAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OpenIddict.EntityFramework.OpenIddictTokenStore`5.<BindAsync>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OpenIddict.EntityFramework.OpenIddictTokenStore`5.<CreateAsync>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OpenIddict.Core.OpenIddictTokenManager`1.<CreateAsync>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OpenIddict.OpenIddictProvider`4.<CreateTokenAsync>d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OpenIddict.OpenIddictProvider`4.<SerializeRefreshToken>d__44.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<SerializeRefreshTokenAsync>d__29.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<SignInAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.<SignInAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.SignInResult.<ExecuteResultAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n

**Comment by kevinchalet** [comment] 2017-11-06 13:59
I presume you're using custom entities? Can you share them? A screenshot of the `OpenIddictTokens` table definition would also help.

**Comment by Gillardo** [comment] 2017-11-06 14:01
Nope, not using any custom entities (apart from my own User) entity, but that doesnt effect anything i believe.  This is just using all the EF6 stores and models

Tables for you
![image](https://user-images.githubusercontent.com/7406381/32444552-04c85fea-c2fb-11e7-879b-d04930290d70.png)

![image](https://user-images.githubusercontent.com/7406381/32444542-f589a99e-c2fa-11e7-8e89-94f9947181a9.png)

![image](https://user-images.githubusercontent.com/7406381/32444539-f09d3ffe-c2fa-11e7-98e7-d8bcf849aaf8.png)

![image](https://user-images.githubusercontent.com/7406381/32444533-eaefceaa-c2fa-11e7-989b-a23345c3bb87.png)

**Comment by kevinchalet** [comment] 2017-11-06 14:11
It's a bug in the EF 6.x store, caused by the fact `FindAsync` has a different definition than the EF Core version:

EF 6.x: 

```csharp
Task<TEntity> FindAsync(CancellationToken cancellationToken, params object[] keyValues);
```

EF Core:

```csharp
Task<TEntity> FindAsync(object[] keyValues, CancellationToken cancellationToken);
```

So instead of using `await Applications.FindAsync(new object[] { ConvertIdentifierFromString(descriptor.ApplicationId) }, cancellationToken);`, we should use `await Applications.FindAsync(cancellationToken, ConvertIdentifierFromString(descriptor.ApplicationId));`.

The fix will be available today and uploaded to the MyGet feed.

**Comment by Gillardo** [comment] 2017-11-06 14:15
@PinpointTownes that is fine... i was more worried i had done something myself.  Could you drop me an email when it is available please?

**Comment by Gillardo** [comment] 2017-11-07 09:51
Any news on this @PinpointTownes ?

**Comment by kevinchalet** [comment] 2017-11-07 12:38
PR merged. Give Appveyor a few minutes to build new packages and give them a try :smile:

**Closed as completed by kevinchalet** 2017-11-07 12:38 UTC
Labels: bug

**Comment by Gillardo** [comment] 2017-11-07 12:41
thank you!

**Comment by kevinchalet** [comment] 2017-11-07 15:53
@Gillardo did you have a chance to try the latest version?

**Comment by Gillardo** [comment] 2017-11-07 15:55
Yes @PinpointTownes  worked perfectly! thank you again!

**Comment by kevinchalet** [comment] 2017-11-07 15:56
Great, thanks for confirming :+1:

**Comment by Gillardo** [comment] 2017-11-07 15:57
sorry should of wrote back straight away but bit mental today.... like always 😄
