### ISSUE TITLE
not able to run the samples

### ISSUE THREAD

**Issue by kairohmer** [openiddict/openiddict-core#78] opened 2016-03-23 21:17 UTC
Hi,
after the last update today I was able to build the entire solution. But when running the Server, I get an exception in OpenIddict.Core\OpenIddictExtensions.cs line 152

This is the nicely formatted error page ;)
[500 Internal Server Error.zip](https://github.com/openiddict/openiddict-core/files/186866/500.Internal.Server.Error.zip)

**Comment by kevinchalet** [comment] 2016-03-23 21:26
Yo. 

This ticket is a duplicate of https://github.com/openiddict/openiddict-core/issues/77.
It will be fixed by https://github.com/aspnet/Logging/pull/395.

**Closed as completed by kevinchalet** 2016-03-23 21:26 UTC
Labels: bug, external
