### ISSUE TITLE
Destination array is not long enough to copy all the items in the collection. Check array index and length.

### ISSUE THREAD

**Issue by maliming** [openiddict/openiddict-core#1577] opened 2022-11-15 13:59 UTC
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

`4.0.0-preview5.22557.92`

### Describe the bug

There seems to be a problem with the code here.

https://github.com/openiddict/openiddict-core/blob/51c09bec8a3bea75d8d72ad5c18c81d4e40e5a9b/src/OpenIddict.Server/OpenIddictServerHandlers.Protection.cs#L1330-L1336

### Exceptions (if any)

```cs
Destination array is not long enough to copy all the items in the collection. Check array index and length. (Parameter 'value')

at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at OpenIddict.Server.OpenIddictServerHandlers.Protection.ConvertReferenceToken.HandleAsync(GenerateTokenContext context)
   at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Server.OpenIddictServerHandlers.GenerateUserCode.HandleAsync(ProcessSignInContext context)
   at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Server.OpenIddictServerHandlers.Device.HandleDeviceRequest.HandleAsync(ProcessRequestContext context)
   at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by kevinchalet** [comment] 2022-11-15 20:39
Thanks for the report, @maliming.

This regression (_12 bits vs 12 bytes_ 😅 ) was caused by https://github.com/openiddict/openiddict-core/pull/1556. I'll make sure it's fixed in the next preview, as it prevents the device code flow from working properly.

**Closed as completed** 2022-11-16 03:10 UTC
Labels: bug, sponsor

**Comment by kevinchalet** [comment] 2022-11-16 17:04
@maliming FYI, OpenIddict 4.0 preview6 was just pushed to NuGet.org: https://github.com/openiddict/openiddict-core/releases/tag/4.0.0-preview6

https://www.nuget.org/packages/OpenIddict.Server/4.0.0-preview6.22566.67

Cheers.

**Comment by maliming** [comment] 2022-11-17 00:32
Thanks @kevinchalet , I will update it asap.
