### ISSUE TITLE
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.OpenIdToken_dbo.OpenIdApplication_ApplicationId"

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#344] opened 2017-01-25 09:40 UTC
I have just updated to the latest version of openIddict-core.  I have had to update my custom Application and Token stores because there are now new interface methods (which i basically copied from the src folder).

Now if i try to login, i am getting the exception

> The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.OpenIdToken_dbo.OpenIdApplication_ApplicationId"

This seems to happen in this method, as the Application nor ApplicationId has been set??  Should it be set already?  Am i supposed to be setting this myself now somewhere else??

I am using refresh tokens... not sure if that helps?

```
public virtual async Task<Token> CreateAsync(Token token, CancellationToken cancellationToken)
{
	if (token == null)
	{
		throw new ArgumentNullException(nameof(token));
	}

	_context.SetAdded(token);

	await _context.SaveChangesAsync();

	return token;
}
```

**Comment by kevinchalet** [comment] 2017-01-25 11:54
Have you updated your database schema to include the new columns?

**Comment by Gillardo** [comment] 2017-01-25 11:56
Updated my models with anything i think it needs (if it says it was missing i added it)

![image](https://cloud.githubusercontent.com/assets/7406381/22289791/4a1081d6-e2f5-11e6-85c7-c6b5d6b94d9e.png)

**Comment by kevinchalet** [comment] 2017-01-25 12:05
What's the ORM you're using?

Note: I see a few missing columns, like `Subject` or `ApplicationId` in the `OpenIdAuthorization` table.

**Comment by Gillardo** [comment] 2017-01-25 12:12
EF 6.1

Here are my objects

```
public class Application
{
	/// <summary>
	/// Id of the application
	/// </summary>
	public long Id { get; set; }

	/// <summary>
	/// Name of the application
	/// </summary>
	public string Name { get; set; }

	/// <summary>
	/// Type of application (public or confidential)
	/// </summary>
	public string Type { get; set; }

	/// <summary>
	/// Client Id for application
	/// </summary>
	public string ClientId { get; set; }

	/// <summary>
	/// Hashed client secret
	/// </summary>
	public string ClientSecret { get; set; }

	/// <summary>
	/// Uri to redirect to 
	/// </summary>
	public string RedirectUri { get; set; }

	/// <summary>
	/// Uri to redirect to when logging out
	/// </summary>
	public string LogoutRedirectUri { get; set; }

	/// <summary>
	/// Gets the list of the tokens associated with this application.
	/// </summary>
	public ICollection<Token> Tokens { get; set; }
}
```

```
public class Authorization
{
	/// <summary>
	/// Gets or sets the unique identifier associated with the current authorization
	/// </summary>
	public string Id { get; set; }

	/// <summary>
	/// Gets or sets the space-delimited scopes associated with the current authorization
	/// </summary>
	public string Scope { get; set; }

	/// <summary>
	/// Gets or sets the list of tokens associated with the current authorization
	/// </summary>
	public virtual ICollection<Token> Tokens { get; set; }

	public Authorization()
	{
		Id = System.Guid.NewGuid().ToString();
	}
}
```

```
public class Scope
{
	/// <summary>
	/// Gets or sets the unique identifier
	/// associated with the current scope
	/// </summary>
	public string Id { get; set; }

	/// <summary>
	/// Gets or sets the public description
	/// associated with the current scope
	/// </summary>
	public string Description { get; set; }

	public Scope()
	{
		Id = System.Guid.NewGuid().ToString();
	}
}
```

```
public class Token
{
	/// <summary>
	/// Gets or sets the unique identifier associated with the current token
	/// </summary>
	public string Id { get; set; }

	/// <summary>
	/// Id of the authorization that this token is associated with
	/// </summary>
	public string AuthorizationId { get; set; }

	/// <summary>
	/// Authorization that this token is associated with
	/// </summary>
	public virtual Authorization Authorization { get; set; }

	/// <summary>
	/// Id of the application that this token is assoicated with
	/// </summary>
	public long ApplicationId { get; set; }

	/// <summary>
	/// Application that this token is assoicated with
	/// </summary>
	public virtual Application Application { get; set; }

	/// <summary>
	/// Gets or sets the type of the current token
	/// </summary>
	public string Type { get; set; }

	/// <summary>
	/// Gets or sets the subject associated with the current token
	/// </summary>
	public string Subject { get; set; }

	public Token()
	{
		Id = System.Guid.NewGuid().ToString();
	}
}
```

**Comment by Gillardo** [comment] 2017-01-25 12:15
I see, i believe i am missing application and subject on authorization.... I will add these and see if this works.  Apologies

**Comment by Gillardo** [comment] 2017-01-25 12:24
I have added those fields to authorization, and still no luck, same problem

**Comment by Gillardo** [comment] 2017-01-25 12:25
Here is my updated authorization object

```
public class Authorization
{
	/// <summary>
	/// Gets or sets the unique identifier associated with the current authorization
	/// </summary>
	public string Id { get; set; }

	/// <summary>
	/// Gets or sets the subject associated with the current authorization
	/// </summary>
	public string Subject { get; set; }

	/// <summary>
	/// Gets or sets the space-delimited scopes associated with the current authorization
	/// </summary>
	public string Scope { get; set; }

	/// <summary>
	/// Gets or sets the application id
	/// </summary>
	public long ApplicationId { get; set; }

	/// <summary>
	/// Gets or sets the application
	/// </summary>
	public Application Application { get; set; }

	/// <summary>
	/// Gets or sets the list of tokens associated with the current authorization
	/// </summary>
	public virtual ICollection<Token> Tokens { get; set; }

	public Authorization()
	{
		Id = System.Guid.NewGuid().ToString();
	}
}
```

**Comment by Gillardo** [comment] 2017-01-25 12:25
Would it be helpful if i upload my custom stores?  Although they are basically copies of yours

**Comment by kevinchalet** [comment] 2017-01-25 12:35
Yes, please provide a minimal, complete, and verifiable example.

FYI, I'm considering adding "official" support for EF6 in the future if there's enough demand.

**Comment by Gillardo** [comment] 2017-01-25 13:08
Will take some time to create an example project, as my project uses angular2 and is built upon our service code.

For the moment, i can upload copies of the stores i have wrote, but i believe these are all correct.  Your more then welcome to use these if it helps to implement EF6 functionality.

I have only implemented stores for Application and Token

```
/// <summary>
/// OpenId application store
/// </summary>
public class OpenIdApplicationStore : IOpenIddictApplicationStore<Application>
{
	#region IOpenIddictApplicationStore

	/// <summary>
	/// Creates a new application.
	/// </summary>
	/// <param name="application"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public async Task<Application> CreateAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		_context.Application.Add(application);

		await _context.SaveChangesAsync();

		return application;
	}

	/// <summary>
	/// Removes an existing application.
	/// </summary>
	/// <param name="application">The application to delete.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation.
	/// </returns>
	public async Task DeleteAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		_context.Application.Remove(application);

		await _context.SaveChangesAsync();
	}

	/// <summary>
	/// Retrieves an application using its client identifier.
	/// </summary>
	/// <param name="identifier"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task<Application> FindByClientIdAsync(string identifier, CancellationToken cancellationToken)
	{
		return _context.Application
			.Where(e => e.ClientId == identifier)
			.FirstOrDefaultAsync();
	}

	/// <summary>
	/// Retrieves an application using its unique identifier.
	/// </summary>
	/// <param name="identifier"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task<Application> FindByIdAsync(string identifier, CancellationToken cancellationToken)
	{
		var key = ConvertIdentifierFromString<long>(identifier);

		return _context.Application
			.Where(e => e.Id == key)
			.FirstOrDefaultAsync();
	}

	/// <summary>
	/// Retrieves an application using its post_logout_redirect_uri.
	/// </summary>
	/// <param name="url"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task<Application> FindByLogoutRedirectUri(string url, CancellationToken cancellationToken)
	{
		return _context.Application
			.Where(e => e.LogoutRedirectUri == url)
			.FirstOrDefaultAsync();
	}

	/// <summary>
	/// Retrieves the client identifier associated with an application.
	/// </summary>
	/// <param name="application">The application.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
	/// whose result returns the client identifier associated with the application.
	/// </returns>
	public Task<string> GetClientIdAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		return Task.FromResult(application.ClientId);
	}

	/// <summary>
	/// Retrieves the client type associated with an application.
	/// </summary>
	/// <param name="application"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task<string> GetClientTypeAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		return Task.FromResult(application.Type);
	}

	/// <summary>
	/// Retrieves the display name associated with an application.
	/// </summary>
	/// <param name="application"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task<string> GetDisplayNameAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		return Task.FromResult(application.Name);
	}

	/// <summary>
	/// Retrieves the hashed secret associated with an application.
	/// </summary>
	/// <param name="application"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task<string> GetHashedSecretAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		return Task.FromResult(application.ClientSecret);
	}

	/// <summary>
	/// Retrieves the unique identifier associated with an application.
	/// </summary>
	/// <param name="application">The application.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
	/// whose result returns the unique identifier associated with the application.
	/// </returns>
	public virtual Task<string> GetIdAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		return Task.FromResult(ConvertIdentifierToString(application.Id));
	}

	/// <summary>
	/// Retrieves the logout callback address associated with an application.
	/// </summary>
	/// <param name="application">The application.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
	/// whose result returns the post_logout_redirect_uri associated with the application.
	/// </returns>
	public Task<string> GetLogoutRedirectUriAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		return Task.FromResult(application.LogoutRedirectUri);
	}

	/// <summary>
	/// Retrieves the callback address associated with an application.
	/// </summary>
	/// <param name="application"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task<string> GetRedirectUriAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		return Task.FromResult(application.RedirectUri);
	}

	/// <summary>
	/// Retrieves the token identifiers associated with an application.
	/// </summary>
	/// <param name="application"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public async Task<IEnumerable<string>> GetTokensAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		var tokens = await _context.Application
			.Where(e => e.Id == application.Id)
			.SelectMany(e => e.Tokens)
			.Select(e => e.Id.ToString())
			.ToListAsync();

		return tokens;
	}

	/// <summary>
	/// Sets the client type associated with an application.
	/// </summary>
	/// <param name="application">The application.</param>
	/// <param name="type">The client type associated with the application.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation.
	/// </returns>
	public virtual Task SetClientTypeAsync(Application application, string type, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		if (string.IsNullOrEmpty(type))
		{
			throw new ArgumentException("The client type cannot be null or empty.", nameof(type));
		}

		application.Type = type;

		return Task.FromResult(0);
	}

	/// <summary>
	/// Sets the hashed secret associated with an application.
	/// </summary>
	/// <param name="application">The application.</param>
	/// <param name="hash">The hashed client secret associated with the application.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation.
	/// </returns>
	public Task SetHashedSecretAsync(Application application, string hash, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		if (string.IsNullOrEmpty(hash))
		{
			throw new ArgumentException("The client secret hash cannot be null or empty.", nameof(hash));
		}

		application.ClientSecret = hash;

		return Task.FromResult(0);
	}

	/// <summary>
	/// Updates an existing application.
	/// </summary>
	/// <param name="application">The application to update.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation.
	/// </returns>
	public async Task UpdateAsync(Application application, CancellationToken cancellationToken)
	{
		if (application == null)
		{
			throw new ArgumentNullException(nameof(application));
		}

		_context.SetModified(application);

		await _context.SaveChangesAsync();
	}

	#endregion

	#region Class Methods

	/// <summary>
	/// Converts the provided identifier to a strongly typed key object.
	/// </summary>
	/// <param name="identifier">The identifier to convert.</param>
	/// <returns>An instance of long representing the provided identifier.</returns>
	public virtual TKey ConvertIdentifierFromString<TKey>(string identifier)
	{
		if (string.IsNullOrEmpty(identifier))
		{
			return default(TKey);
		}

		return (TKey)TypeDescriptor.GetConverter(typeof(TKey))
									.ConvertFromInvariantString(identifier);
	}

	/// <summary>
	/// Converts the provided identifier to its string representation.
	/// </summary>
	/// <param name="identifier">The identifier to convert.</param>
	/// <returns>A <see cref="string"/> representation of the provided identifier.</returns>
	public virtual string ConvertIdentifierToString<TKey>(TKey identifier)
	{
		if (Equals(identifier, default(TKey)))
		{
			return null;
		}

		return TypeDescriptor.GetConverter(typeof(TKey))
							 .ConvertToInvariantString(identifier);
	}

	#endregion

	private IDataContext _context;

	/// <summary>
	/// Create open Id application store
	/// </summary>
	/// <param name="context"></param>
	public OpenIdApplicationStore(IDataContext context)
	{
		_context = context;
	}
}
```

```
/// <summary>
/// OpenId token store
/// </summary>
public class OpenIdTokenStore : IOpenIddictTokenStore<Token>
{
	#region IOpenIddictTokenStore

	/// <summary>
	/// Creates a new token.
	/// </summary>
	/// <param name="token">The token to create.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation, whose result returns the token.
	/// </returns>
	public virtual async Task<Token> CreateAsync(Token token, CancellationToken cancellationToken)
	{
		if (token == null)
		{
			throw new ArgumentNullException(nameof(token));
		}

		_context.SetAdded(token);

		await _context.SaveChangesAsync();

		return token;
	}

	/// <summary>
	/// Creates a new token, which is associated with a particular subject.
	/// </summary>
	/// <param name="type">The token type.</param>
	/// <param name="subject">The subject associated with the token.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation, whose result returns the token.
	/// </returns>
	public virtual Task<Token> CreateAsync(string type, string subject, CancellationToken cancellationToken)
	{
		if (string.IsNullOrEmpty(type))
		{
			throw new ArgumentException("The token type cannot be null or empty.");
		}

		return CreateAsync(new Token { Subject = subject, Type = type }, cancellationToken);
	}

	/// <summary>
	/// Retrieves an token using its unique identifier.
	/// </summary>
	/// <param name="identifier"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task<Token> FindByIdAsync(string identifier, CancellationToken cancellationToken)
	{
		return _context.Token
			.Where(e => e.Id.ToString() == identifier)
			.FirstOrDefaultAsync();
	}

	/// <summary>
	/// Retrieves the list of tokens corresponding to the specified subject.
	/// </summary>
	/// <param name="subject">The subject associated with the tokens.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
	/// whose result returns the tokens corresponding to the specified subject.
	/// </returns>
	public virtual Task<Token[]> FindBySubjectAsync(string subject, CancellationToken cancellationToken)
	{
		return _context.Token.Where(token => token.Subject == subject).ToArrayAsync();
	}

	/// <summary>
	/// Retrieves the unique identifier associated with a token.
	/// </summary>
	/// <param name="token">The token.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
	/// whose result returns the unique identifier associated with the token.
	/// </returns>
	public virtual Task<string> GetIdAsync(Token token, CancellationToken cancellationToken)
	{
		if (token == null)
		{
			throw new ArgumentNullException(nameof(token));
		}

		return Task.FromResult(ConvertIdentifierToString(token.Id));
	}

	/// <summary>
	/// Retrieves the token type associated with a token.
	/// </summary>
	/// <param name="token">The token.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
	/// whose result returns the token type associated with the specified token.
	/// </returns>
	public virtual Task<string> GetTokenTypeAsync(Token token, CancellationToken cancellationToken)
	{
		if (token == null)
		{
			throw new ArgumentNullException(nameof(token));
		}

		return Task.FromResult(token.Type);
	}

	/// <summary>
	/// Retrieves the subject associated with a token.
	/// </summary>
	/// <param name="token">The token.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation,
	/// whose result returns the subject associated with the specified token.
	/// </returns>
	public virtual Task<string> GetSubjectAsync(Token token, CancellationToken cancellationToken)
	{
		if (token == null)
		{
			throw new ArgumentNullException(nameof(token));
		}

		return Task.FromResult(token.Subject);
	}

	/// <summary>
	/// Revokes a token.
	/// </summary>
	/// <param name="token"></param>
	/// <param name="cancellationToken"></param>
	/// <returns></returns>
	public Task RevokeAsync(Token token, CancellationToken cancellationToken)
	{
		if (token == null)
		{
			throw new ArgumentNullException(nameof(token));
		}

		_context.Token.Remove(token);

		return _context.SaveChangesAsync();
	}

	/// <summary>
	/// Sets the authorization associated with a token.
	/// </summary>
	/// <param name="token">The token.</param>
	/// <param name="identifier">The unique identifier associated with the authorization.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation.
	/// </returns>
	public virtual async Task SetAuthorizationAsync(Token token, string identifier, CancellationToken cancellationToken)
	{
		if (token == null)
		{
			throw new ArgumentNullException(nameof(token));
		}

		if (!string.IsNullOrEmpty(identifier))
		{
			var key = ConvertIdentifierFromString<string>(identifier);
			var authorization = await _context.Authorization.SingleOrDefaultAsync(element => element.Id.Equals(key));

			if (authorization == null)
			{
				throw new InvalidOperationException("The authorization associated with the token cannot be found.");
			}

			authorization.Tokens.Add(token);
		}

		else
		{
			var key = await GetIdAsync(token, cancellationToken);

			// Try to retrieve the authorization associated with the token.
			// If none can be found, assume that no authorization is attached.
			var authorization = await _context.Authorization.SingleOrDefaultAsync(element => element.Tokens.Any(t => t.Id.Equals(key)));

			if (authorization != null)
			{
				authorization.Tokens.Remove(token);
			}
		}
	}

	/// <summary>
	/// Sets the client application associated with a token.
	/// </summary>
	/// <param name="token">The token.</param>
	/// <param name="identifier">The unique identifier associated with the client application.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation.
	/// </returns>
	public virtual async Task SetClientAsync(Token token, string identifier, CancellationToken cancellationToken)
	{
		if (token == null)
		{
			throw new ArgumentNullException(nameof(token));
		}

		if (!string.IsNullOrEmpty(identifier))
		{
			var key = ConvertIdentifierFromString<string>(identifier);

			var application = await _context.Application.SingleOrDefaultAsync(element => element.Id.Equals(key));

			if (application == null)
			{
				throw new InvalidOperationException("The application associated with the token cannot be found.");
			}

			application.Tokens.Add(token);
		}

		else
		{
			var key = await GetIdAsync(token, cancellationToken);

			// Try to retrieve the application associated with the token.
			// If none can be found, assume that no application is attached.
			var application = await _context.Application.SingleOrDefaultAsync(element => element.Tokens.Any(t => t.Id.Equals(key)));

			if (application != null)
			{
				application.Tokens.Remove(token);
			}
		}
	}

	/// <summary>
	/// Updates an existing token.
	/// </summary>
	/// <param name="token">The token to update.</param>
	/// <param name="cancellationToken">The <see cref="CancellationToken"/> that can be used to abort the operation.</param>
	/// <returns>
	/// A <see cref="Task"/> that can be used to monitor the asynchronous operation.
	/// </returns>
	public virtual async Task UpdateAsync(Token token, CancellationToken cancellationToken)
	{
		if (token == null)
		{
			throw new ArgumentNullException(nameof(token));
		}

		_context.SetModified(token);

		try
		{
			await _context.SaveChangesAsync();
		}

		catch (DbUpdateConcurrencyException) { }
	}

	#endregion

	#region Class Methods

	/// <summary>
	/// Converts the provided identifier to a strongly typed key object.
	/// </summary>
	/// <param name="identifier">The identifier to convert.</param>
	/// <returns>An instance of long representing the provided identifier.</returns>
	public virtual TKey ConvertIdentifierFromString<TKey>(string identifier) 
	{
		if (string.IsNullOrEmpty(identifier))
		{
			return default(TKey);
		}

		return (TKey)TypeDescriptor.GetConverter(typeof(TKey))
									.ConvertFromInvariantString(identifier);
	}

	/// <summary>
	/// Converts the provided identifier to its string representation.
	/// </summary>
	/// <param name="identifier">The identifier to convert.</param>
	/// <returns>A <see cref="string"/> representation of the provided identifier.</returns>
	public virtual string ConvertIdentifierToString<TKey>(TKey identifier)
	{
		if (Equals(identifier, default(TKey)))
		{
			return null;
		}

		return TypeDescriptor.GetConverter(typeof(TKey))
							 .ConvertToInvariantString(identifier);
	}

	#endregion

	private IDataContext _context;

	/// <summary>
	/// Create openId token store
	/// </summary>
	/// <param name="context"></param>
	public OpenIdTokenStore(IDataContext context)
	{
		_context = context;
	}
}
```

**Comment by Gillardo** [comment] 2017-01-25 13:32
Have even created a custom AuthorizationStore, but still not working...  No idea what has changed as my stores were fine

**Comment by kevinchalet** [comment] 2017-01-25 13:39
Have you tried to recreate the database from scratch?

**Comment by Gillardo** [comment] 2017-01-25 13:49
Dropped the tables and recreated them.... no difference.

**Comment by kevinchalet** [comment] 2017-01-25 14:30
Ping me when you have a chance to make a tiny repro. I'll take a look.

**Comment by Bartmax** [comment] 2017-01-25 20:16
Why are you creating your custom models ? I think you only need the Application,Authorization,Scope and Token store.

**Comment by Gillardo** [comment] 2017-01-25 20:28
Needed to create own models as my EF 6.1 is in a separate project to openIddict and also I did have them as using long for the key.. but now using string on token, authorization and scope now

**Comment by kevinchalet** [comment] 2017-01-30 20:17
Closing, as this issue doesn't seem to be actionable ATM. I'll re-open if/when you have a chance to share a repro.

**Closed as completed by kevinchalet** 2017-01-30 20:17 UTC

**Comment by Gillardo** [comment] 2017-09-13 12:00
This seems to have come up again, now that i have updated my code.  And i am wondering if it exists in your code, but your using "string" keys, i am using long.  

Anyway, i would like to know when is the `Token.ApplicationId` value set, because mine is always set to 0, so to fix this, i have added the following code to my `OpenIdTokenStore.cs` file.

```
public virtual async Task<TToken> CreateAsync(TToken token, CancellationToken cancellationToken)
{
	if (token == null)
	{
		throw new ArgumentNullException(nameof(token));
	}

	// added to fix issue
	var application = await _context.Application.FirstOrDefaultAsync();
	token.ApplicationId = application.Id;
	// end fix

	_context.Entry(token).State = EntityState.Added;

	await _context.SaveChangesAsync();

	return token;
}
```

Any ideas would be helpful.  I have copied the ApplicationStore, AuthorizationStore and TokenStore from you src, and just changed the way the save call is made, so it works with EF6

**Comment by kevinchalet** [comment] 2017-09-27 17:56
@Gillardo have you configured your context to manually disable changes tracking? The default stores won't work without it. If you absolutely want to turn it off, what you're doing to work around the lack of automatic tracking is the best approach.

FYI, both OpenIddict 1.x and 2.x now have official stores for Entity Framework 6.x that use the default entities. They can be found in the `OpenIddict.EntityFramework` package and work the same way as their Core equivalent, with a few limitations (caused by EF 6.x):

  - You must manually register your `DbContext` as a scoped dependency in the ASP.NET Core DI container:

```csharp
services.AddScoped(_ =>
    new ApplicationDbContext(configuration["Data:DefaultConnection:ConnectionString"]));
```

  - The entities must be registered from `ApplicationDbContext.OnModelCreating()` by calling `builder.UseOpenIddict()`.

  - There's no `builder.UseOpenIddict<TKey>()` overload like in the EF Core package. If you want to change the default key type, you have to subclass the default entities as EF 6.x refuses to consider closed generic types as valid entities:

```csharp
public class MyApplication : OpenIddictApplication<long, MyAuthorization, MyToken> { }

public class MyAuthorization : OpenIddictAuthorization<long, MyApplication, MyToken> { }

public class MyScope : OpenIddictScope<long> { }

public class MyToken : OpenIddictToken<long, MyApplication, MyAuthorization> { }
```

```csharp
protected override void OnModelCreating(DbModelBuilder builder)
{
    base.OnModelCreating(builder);

    builder.UseOpenIddict<MyApplication, MyAuthorization, MyScope, MyToken, long>();
}
```

```csharp
services.AddOpenIddict<MyApplication, MyAuthorization, MyScope, MyToken>(...);
```

**Comment by Gillardo** [comment] 2017-09-28 14:40
@PinpointTownes yes i have stopped change tracking!  This must be the issue.  

I will have a look at implementing the new EF6 stores, since you have now created them! thanks again.  will keep you updated!
