### ISSUE TITLE
Refresh token cannot be found in the database.

### ISSUE THREAD

**Issue by Materix** [openiddict/openiddict-core#698] opened 2018-11-23 15:38 UTC
I have two tests. Both perform refreshing token. When I run it one after another, the second one always fails with response:
```
{
  "error":"invalid_grant",
  "error_description":"The specified refresh token is invalid."
}
```
and in logs I have message:
```
OpenIddict.Server.Internal.OpenIddictServerProvider: Information: The token '1' cannot be found in the database.
```

After digging I found that `OpenIddictTokenStore.FindByIdAsync` during second test returns `null`
Watch window with defined watches when stopped on first line of `OpenIddictTokenStore.FindByIdAsync([NotNull] string, CancellationToken)`

![obraz](https://user-images.githubusercontent.com/6151485/48950934-1807ad80-ef3d-11e8-8a14-9ffa54c394be.png)
As you can see converted identifier is `1` as same as `Id` property in `DbContext`. But somehow `FindById` returns `null`.

Code of tests:
```c#
[Fact]
        public async Task ChangeRole()
        {
            // Given
            var (accessToken, refreshToken) = await RetrieveToken(SuperUser, UserPassword);

            // When
            var request = new HttpRequestMessage(HttpMethod.Post, TestConstants.ServerAddress + AuthorizationConstants.TokenPath);
            request.Headers.Add("Authorization", "Bearer " + accessToken);
            var content = new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>("grant_type", "refresh_token"),
                new KeyValuePair<string, string>("refresh_token", refreshToken),
                // new KeyValuePair<string, string>("role", UserRole.Analytic)
            };

            var values = await SendRequestWithFormUrlEncodedContent(content, request);

            // Then
            values["access_token"].Should().NotBeNullOrEmpty();
            values["refresh_token"].Should().NotBeNullOrEmpty();

            var jwtToken = _handler.ReadJwtToken(values["access_token"]);
            jwtToken.Claims
                    .Should()
                    .ContainSingle(c => c.Type == AuthorizationConstants.CurrentRoleClaim)
                    .Which.Value
                    .Should()
                    .Be(UserRole.Analytic);
        }

        [Fact]
        public async Task RefreshToken()
        {
            // Given
            var (accessToken, refreshToken) = await RetrieveToken(SuperUser, UserPassword);

            // When
            var request = new HttpRequestMessage(HttpMethod.Post, TestConstants.ServerAddress + AuthorizationConstants.TokenPath);
            request.Headers.Add("Authorization", "Bearer " + accessToken);
            var content = new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>("grant_type", "refresh_token"),
                new KeyValuePair<string, string>("refresh_token", refreshToken)
            };

            var values = await SendRequestWithFormUrlEncodedContent(content, request);

            // Then
            values["access_token"].Should().NotBeNullOrEmpty();
            values["refresh_token"].Should().NotBeNullOrEmpty();

            var me = await GetRequest<UserResourceDto>($"{TestConstants.ServerAddress}/api/users/me", values["access_token"]);
            me.Should().NotBeNull();
        }

        protected async Task<Dictionary<string, string>> SendRequestWithFormUrlEncodedContent(List<KeyValuePair<string, string>> headers, HttpRequestMessage request)
        {
            var formUrlEncodedContent = new FormUrlEncodedContent(headers);
            formUrlEncodedContent.Headers.ContentType.MediaType = "application/x-www-form-urlencoded";
            request.Content = formUrlEncodedContent;
            var response = await Client.SendAsync(request);

            return await ReadRawResult<Dictionary<string, string>>(response);
        }
```

Tests were performed on separated InMemory database and separated TestServer (for each test new db and server were created). On production with SqlServer there is no problem in consecutive refreshing token

Version OpenIddict: 2.0.0

Edit: This tests work on 2.0.0-rc2-final without any problems

**Comment by kevinchalet** [comment] 2018-11-28 15:40
Hard to tell without having a repro. Would you mind posting a minimal one on GitHub? (one that builds and runs, please :smile:)

**Comment by Materix** [comment] 2018-11-29 09:29
I prepared demo project on https://github.com/Materix/OpenIddict698

AuthorizationController is a copy of AuthorizationController from https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Controllers/AuthorizationController.cs

If you run both tests at once, one of then fails. If then you run this failed test alone, it will succeeded

**Comment by kevinchalet** [comment] 2018-12-15 19:59
Thanks for the repro. I can confirm I'm seeing the same weird thing.

After spending 2 hours on that, my conclusion is that it's likely not caused by OpenIddict itself but by a strange bug in EF Core's in-memory stores that seems to impact compiled queries, massively used in OpenIddict since RC3: https://github.com/aspnet/EntityFrameworkCore/issues/13483 (kudos to @JanEggers for his excellent investigation).

Let's keep an eye on the EF Core bug to see if it may be fixed in the near future.

**Closed as completed** 2019-01-21 15:29 UTC
Labels: bug, external

**Comment by kevinchalet** [comment] 2019-10-17 18:26
Note: as part of 2.0.1 and 3.x, I removed the compiled queries from the EF Core stores, so this error should disappear when migrating your apps.
