### ISSUE TITLE
Is there a way to enforce the usage of PKCE for the authorization code flow ?

### ISSUE THREAD

**Issue by jonathanantoine** [openiddict/openiddict-core#716] opened 2019-01-15 16:28 UTC
Hello,

Is there a way to enforce the usage of PKCE for the authorization code flow ?
Do I have to check it manually ?

Thanks !

**Comment by kevinchalet** [comment] 2019-01-15 18:02
Hey,

When I added PKCE support 3 years ago, I decided against adding a flag to make its use mandatory, mostly because client support was completely inexistant and because PKCE was designed as an "additive" security feature, that would benefit to clients supporting it without breaking existing clients (which would have been terrible).

Now, 3 years later, things have - luckily - changed a bit: client support is much wider and [we're now envisioning using PKCE for scenarios it wasn't designed for (at all)](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-11), including helping protect non-native applications (e.g to prevent authorization codes from being stolen and redeemed by an attacker).

Adding a native option to make it mandatory would certainly be a good idea and it should be fairly trivial to add, so let's add it to the todo list :smile: 

In the meantime, it's not hard to add it yourself, in your authorization controller or in an event handler:

```csharp
services.AddOpenIddict()

    // Register the OpenIddict core services.
    .AddCore(options =>
    {
        // ...
    })

    // Register the OpenIddict server handler.
    .AddServer(options =>
    {
        // ...

        options.AddEventHandler<OpenIddictServerEvents.ValidateAuthorizationRequest>(
            notification =>
            {
                var request = notification.Context.Request;

                // Don't reject implicit flow requests (that can't use PKCE by definition).
                if (!request.IsAuthorizationCodeFlow() && !request.IsHybridFlow())
                {
                    return Task.FromResult(OpenIddictServerEventState.Unhandled);
                }

                if (string.IsNullOrEmpty(request.CodeChallenge))
                {
                    notification.Context.Reject(
                        error: OpenIddictConstants.Errors.InvalidRequest,
                        description: "This server requires using PKCE for code and hybrid requests.");

                    return Task.FromResult(OpenIddictServerEventState.Handled);
                }

                return Task.FromResult(OpenIddictServerEventState.Unhandled);
            });
    });
```

**Comment by jonathanantoine** [comment] 2019-01-15 19:19
Thanks for answering me! I added a check in my authorization endpoint instead of where you pointed me and it will works while we have the proper release. Do you want me to work on it and create a PR?

**Comment by kevinchalet** [comment] 2019-01-15 19:41
@jonathanantoine here we go: https://github.com/openiddict/openiddict-core/pull/717

It will be introduced in 3.0, but depending on the demand, this feature may be backported to 1.x and 2.x at a later date.

**Comment by jonathanantoine** [comment] 2019-01-17 13:53
I would love to have it in 2.0 :)

**Closed as completed** 2019-01-26 20:09 UTC
Labels: enhancement
