### ISSUE TITLE
Something broken when using with dotnet cli?

### ISSUE THREAD

**Issue by Gillardo** [openiddict/openiddict-core#84] opened 2016-04-11 09:50 UTC
Like everyone i have now changed to use the dotnet cli and changed my target frameworks from dnx451 to net451.  Since doing this, restoring the latest packages etc, openiddict no longer works.

If i use postman and connect to http://localhost:5000/connect/token with a username and password, this returns an access_token.  Now if i use that access token, i always get a 401 error?

Apart from the url changing to localhost:5000 (which i have updated in my Applications table), nothing else apart from the version has changed.

Upon debugging it seems that the access_token that i am passing it never generates a valid identity on a request?  The IsAuthenticated property is always false and even the username is null.

**Comment by kevinchalet** [comment] 2016-04-11 11:38
It's not caused by CLI, but by a bug in IdentityModel.

More context:
https://github.com/capesean/openiddict-test/issues/8
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/232
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/360

The bug was fixed recently by the AzureAD team, but the updated package is not on the aspnetcidev feed we use. I hope it will be fixed soon by the ASP.NET team.

**Comment by kevinchalet** [comment] 2016-04-12 15:14
The aspnet-contrib feed is now mirroring the Azure AD feed and ASOS was just updated to use the latest IdentityModel packages: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/e3a8781af075157af944d575d441bab3e7773a05.

The JWT issue you're seeing should disappear when updating your packages.

**Closed as completed by kevinchalet** 2016-04-12 15:14 UTC
Labels: bug, external
