### ISSUE TITLE
Specific token query performance issue

### ISSUE THREAD

**Issue by BlackSyc** [openiddict/openiddict-core#1381] opened 2022-02-01 15:48 UTC
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

We've had issues where our OpenIddict 3.1.1 server periodically completely crashes due to query timeouts on a specific query. 
The database usage does not exceed 25%, so I'm doubtful it's caused by a database issue.

The query that seems to be causing the issues is:
`(@__key_0 uniqueidentifier)
SELECT [t].[Id],
       [t].[ApplicationId],
       [t].[AuthorizationId],
       [t].[ConcurrencyToken],
       [t].[CreationDate],
       [t].[ExpirationDate],
       [t].[Payload],
       [t].[Properties],
       [t].[RedemptionDate],
       [t].[ReferenceId],
       [t].[Status],
       [t].[Subject],
       [t].[Type],
       [t0].[Id],
       [t0].[ClientId],
       [t0].[ClientSecret],
       [t0].[ConcurrencyToken],
       [t0].[ConsentType],
       [t0].[CreatedBy],
       [t0].[CreatedOn],
       [t0].[DeleteOn],
       [t0].[DeletedBy],
       [t0].[DisplayName],
       [t0].[DisplayNames],
       [t0].[IsDeleted],
       [t0].[ModifiedBy],
       [t0].[ModifiedOn],
       [t0].[Permissions],
       [t0].[PostLogoutRedirectUris],
       [t0].[Properties],
       [t0].[RedirectUris],
       [t0].[Requirements],
       [t0].[Type],
       [a].[Id],
       [a].[ApplicationId],
       [a].[ConcurrencyToken],
       [a].[CreationDate],
       [a].[Properties],
       [a].[Scopes],
       [a].[Status],
       [a].[Subject],
       [a].[Type]
FROM [Tokens] AS [t]
         LEFT JOIN [Authorizations] AS [a] ON [t].[AuthorizationId] = [a].[Id]
         INNER JOIN [Authorizations] AS [a0] ON [a].[Id] = [a0].[Id]
         LEFT JOIN (SELECT [a1].[Id],
                           [a1].[ClientId],
                           [a1].[ClientSecret],
                           [a1].[ConcurrencyToken],
                           [a1].[ConsentType],
                           [a1].[CreatedBy],
                           [a1].[CreatedOn],
                           [a1].[DeleteOn],
                           [a1].[DeletedBy],
                           [a1].[DisplayName],
                           [a1].[DisplayNames],
                           [a1].[IsDeleted],
                           [a1].[ModifiedBy],
                           [a1].[ModifiedOn],
                           [a1].[Permissions],
                           [a1].[PostLogoutRedirectUris],
                           [a1].[Properties],
                           [a1].[RedirectUris],
                           [a1].[Requirements],
                           [a1].[Type]
                    FROM [Applications] AS [a1]
                    WHERE [a1].[IsDeleted] <> CAST(1 AS bit)) AS [t0] ON [t].[ApplicationId] = [t0].[Id]
WHERE [a0].[Id] = @__key_0`

As you can see in the image below, this specific query only gets executed at strange intervals, sometimes causing the server to completely crash due to the timeouts.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/16132446/151999806-adc9cc05-886c-4f75-88a1-c07c6a0205b5.png)

I have not been able to find what endpoint is executing this query at all, and why it would trigger these timeouts. When I execute the query on the same database manually, no timeouts occur and results are returned as quick as one would expect (<1s).

The data packages I'm using are shown below:
![afbeelding](https://user-images.githubusercontent.com/16132446/152001022-e3518c8a-ecb2-49a4-a01c-f603101202a9.png)

Let me know if you need any more information.

Could you point me in the right direction as to where to start looking?

**Comment by kevinchalet** [comment] 2022-02-01 16:06
I'd say that SQL query corresponds to the LINQ query used in the `FindByAuthorizationIdAsync()` method:

https://github.com/openiddict/openiddict-core/blob/02c64fdd90d5d5d54e918b508088f3dce74233fb/src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictEntityFrameworkCoreTokenStore.cs#L303-L321

Currently, it's used in only one degenerate case: when OpenIddict detects that a client is trying to replay a token - authorization code, refresh token or device code - that is already marked as "redeemed" in the database. In this case, OpenIddict needs to revoke the entire authorization chain to invalidate everything and for that, it has to find all the tokens associated with the authorization.

I see you used custom entities (not sure why you'd need `IsDeleted/ModifiedBy/etc` properties as they are typically used for soft deletes). Are you able to reproduce that issue with the default entities/stores?

You say this issue crashes the server, which seems strange. Are you sure requests are not blocked due to a deadlock-like issue?

**Comment by BlackSyc** [comment] 2022-02-02 11:10
Thank you for the quick response. 

This does help me narrow down where the issue is coming from.

I found that for one user there are about 18500 tokens present for a particular authorization, and for many other users there are well over 1000 tokens present as well. I'm thinking that when a client is trying to replay a token like you said, the server is fetching all these tokens (which takes a few seconds) and then trying to revoke them one by one which takes a long time. It may be possible that during that time the client has performed another such request (and again and again), which would cause an increasingly big load on the server.

I'm therefore wondering if those tokens should be cleaned up in any way? Or is it possible that I'm doing something wrong that makes it hold on to so many tokens? (As said, in this case, it's all for one particular authorization)

I am indeed using auditing properties (IsDeleted/ModifiedBy/etc) but only for the applications and users themselves. This is because we allow creating/updating/removing applications at runtime in a management portal.

I have not been able to reproduce the issue in a development environment, which, I think, could be explained by the fact that I'd first need this many tokens in the database?

**Comment by kevinchalet** [comment] 2022-02-02 13:50
Sounds like a good explanation 😄 

> I'm therefore wondering if those tokens should be cleaned up in any way?

Yes. The recommended option is Quartz.NET:
  - https://github.com/openiddict/openiddict-samples/blob/5119f8f5e392244a50eed8344f1bf40f12a34692/samples/Velusia/Velusia.Server/Startup.cs#L62-L72
  - https://github.com/openiddict/openiddict-samples/blob/5119f8f5e392244a50eed8344f1bf40f12a34692/samples/Velusia/Velusia.Server/Startup.cs#L84-L85

If you don't like it, you can also call the pruning APIs yourself.

**Comment by BlackSyc** [comment] 2022-02-02 14:45
Ah it seems I completely missed that part.

I will add the pruning job through Quartz, thank you!

**Comment by kevinchalet** [comment] 2022-02-02 14:46
https://github.com/openiddict/openiddict-documentation/issues/38 tracks the work needed to document that. Let me know if you'd be interested in contributing! :smiley:

**Closed as completed** 2022-02-02 14:45 UTC
Labels: question, sponsor

**Comment by BlackSyc** [comment] 2022-04-05 09:10
@kevinchalet I noticed that the OpenIddictTokenManager.PruneAsync method only removes tokens based on their creation date.
I see that, therefore, there are a lot of tokens in the database that are expired (i.e. a lot of access/id tokens, since they have a much shorter lifetime than the refresh tokens).

Wouldn't it be better to just remove tokens that were expired?
If you agree, I could make a pull request for a change like this, but maybe there's a good reason it is implemented this way?

EDIT: another option would be to still prune based on the creation date, but with a different timespan for refresh, access and id-tokens so that the timespan matches the token type's lifetime.

**Comment by BlackSyc** [comment] 2022-04-05 11:59
Never mind, I just browsed the pruning code and I see now that there is in fact an expiration check that happens, only after the minimum token lifetime check.

I misunderstood this part of the documentation. It seems I can just set my minimum lifetime to TimeSpan.Zero for the code to work as I expected.
